export const actionTypes = {
    GET_POSTS_PROG: "GET_POSTS_PROG",
    GET_POSTS_SUCC: "GET_POSTS_SUCC",
    GET_POSTS_FAIL: "GET_POSTS_FAIL",
    
    GET_POST_PROG: "GET_POST_PROG",
    GET_POST_SUCC: "GET_POST_SUCC",
    GET_POST_FAIL: "GET_POST_FAIL",

    CANCEL_POST_REQ: "CANCEL_POST_REQ",
}
